# -*- coding: utf-8 -*-
"""Text Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3gGsbYdH3C2IDGQI-1CN4VHHD8--anF
"""

!pip install streamlit pyngrok
!pip install pyngrok flask
!pip install flask-ngrok pyngrok
from pyngrok import ngrok

from flask_ngrok import run_with_ngrok
from pyngrok import ngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import re
# from collections import Counter
# 
# st.title("📝 Text Analyzer")
# 
# text = st.text_area("Enter or paste your text:",height=200)
# 
# if st.button("🔍 Analyze Text"):
#     if not text.strip():
#         st.error("Please enter some text.")
#     else:
#         # Words
#         words = text.split()
# 
#         # Characters
#         characters = len(text)
# 
#         # Characters without spaces
#         characters_no_spaces = len(text.replace(" ", ""))
# 
#         # Sentences
#         sentences = re.split(r"[.!?]+",text)
# 
#         sentences = [
#             s for s in sentences
#             if s.strip()
#         ]
# 
#         # Most common words
#         clean_words = re.findall(r"\b[a-zA-Z]+\b",text.lower())
# 
#         word_count = Counter(clean_words)
# 
#         col1, col2, col3 = st.columns(3)
# 
#         with col1:
#             st.metric("Words",len(words))
# 
#         with col2:
#             st.metric("Characters",characters)
# 
#         with col3:
#             st.metric("Sentences",len(sentences))
# 
#         st.write(
#             f"Characters without spaces: "
#             f"**{characters_no_spaces}**"
#         )
# 
#         st.subheader("🔥 Most Common Words")
# 
#         common_words = word_count.most_common(10)
# 
#         for word, count in common_words:
#             st.write(f"**{word}** → {count} time(s)")

!pkill -f "streamlit" || true
!pkill -f "ngrok" || true

import time
time.sleep(3)

print("✅ Old Streamlit and ngrok processes stopped.")

from pyngrok import ngrok
import time

# ==========================================
# Configure ngrok
# ==========================================

NGROK_AUTH_TOKEN = "3HxM2dqYoDXKfdntuYQCyDjldxA_2ft3puVvuSrkTKHwx29PU"

ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# ==========================================
# Start Streamlit
# ==========================================

!streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

# Wait for Streamlit to start
time.sleep(5)

# ==========================================
# Create ngrok public tunnel
# ==========================================

tunnel = ngrok.connect(8501)

print("=" * 50)
print("📝 Text Analyzer")
print("=" * 50)
print()
print("🚀 Streamlit is running!")
print()
print("🌐 Public URL:")
print(tunnel.public_url)
print()
print("=" * 50)